#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppCargoExpressFinal.Resource", IsApplication=true)]

namespace AppCargoExpressFinal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::AppCargoExpressFinal.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::AppCargoExpressFinal.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int country_arrays = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camionero = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cargoExpress = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int userIcon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int btnLUAHistorical = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int btnLUAModifyRegister = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btnLUAPublishCargo = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int btnLUAPublishTravel = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int btnLUAReturn = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int btnMLogin = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int btnMLogout = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int btnMhAwardedCargoes = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int btnMhPerformedCargoes = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int btnMhReturn = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int btnMhSeeRank = 2131099672;
			
			// aapt resource value: 0x7f060027
			public const int btnPSRCarrier = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int btnPSRIngresar = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int btnPSRReturn = 2131099690;
			
			// aapt resource value: 0x7f060026
			public const int btnPSRUser = 2131099686;
			
			// aapt resource value: 0x7f06001d
			public const int btnPcfReturn = 2131099677;
			
			// aapt resource value: 0x7f06002f
			public const int btnSubmit = 2131099695;
			
			// aapt resource value: 0x7f060043
			public const int btnURRegister = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int btnURReturn = 2131099716;
			
			// aapt resource value: 0x7f06000e
			public const int chkMRecord = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int imgMView1 = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int lblAcTitle = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int lblMPass = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int lblMRegister = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int lblMUser = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int lblMhMainTitle = 2131099669;
			
			// aapt resource value: 0x7f060021
			public const int lblPSRRegister = 2131099681;
			
			// aapt resource value: 0x7f060028
			public const int lblPSRSelectUserMsg = 2131099688;
			
			// aapt resource value: 0x7f060023
			public const int lblPSRtypeOfUser = 2131099683;
			
			// aapt resource value: 0x7f06001b
			public const int lblPcDateList = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int lblPcNumOperation = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int lblPcOriginDestiny = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int lblPchTitleList = 2131099678;
			
			// aapt resource value: 0x7f06002c
			public const int lblScOrigin = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int lblScTitle = 2131099691;
			
			// aapt resource value: 0x7f06003f
			public const int lblURAddress = 2131099711;
			
			// aapt resource value: 0x7f060035
			public const int lblURAlias = 2131099701;
			
			// aapt resource value: 0x7f060039
			public const int lblURCodArea = 2131099705;
			
			// aapt resource value: 0x7f060041
			public const int lblURComuna = 2131099713;
			
			// aapt resource value: 0x7f06003d
			public const int lblURMail = 2131099709;
			
			// aapt resource value: 0x7f060037
			public const int lblURPhone = 2131099703;
			
			// aapt resource value: 0x7f06003b
			public const int lblURPhone2 = 2131099707;
			
			// aapt resource value: 0x7f060033
			public const int lblURuserLastName = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int lblURuserName = 2131099697;
			
			// aapt resource value: 0x7f060025
			public const int linearLayout1 = 2131099685;
			
			// aapt resource value: 0x7f060001
			public const int lstAc = 2131099649;
			
			// aapt resource value: 0x7f06001f
			public const int lstPcPerformed = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int psrSpc2 = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int spcPSR3 = 2131099684;
			
			// aapt resource value: 0x7f06002d
			public const int spinner1 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int spinner2 = 2131099694;
			
			// aapt resource value: 0x7f06000f
			public const int tblMLayout1 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int tblMRow1 = 2131099664;
			
			// aapt resource value: 0x7f060030
			public const int textView1 = 2131099696;
			
			// aapt resource value: 0x7f060002
			public const int txtLUAWelcomeUser = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int txtMPassword = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int txtMReset = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public const int txtMUserName = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int txtMWelcomeUser = 2131099656;
			
			// aapt resource value: 0x7f060020
			public const int txtPSRWelcomeUser = 2131099680;
			
			// aapt resource value: 0x7f060040
			public const int txtURAddress = 2131099712;
			
			// aapt resource value: 0x7f060036
			public const int txtURAlias = 2131099702;
			
			// aapt resource value: 0x7f06003a
			public const int txtURCodArea = 2131099706;
			
			// aapt resource value: 0x7f060042
			public const int txtURComuna = 2131099714;
			
			// aapt resource value: 0x7f06003e
			public const int txtURMail = 2131099710;
			
			// aapt resource value: 0x7f060038
			public const int txtURPhone = 2131099704;
			
			// aapt resource value: 0x7f06003c
			public const int txtURPhone2 = 2131099708;
			
			// aapt resource value: 0x7f060034
			public const int txtURuserLastName = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int txtURuserName = 2131099698;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AwardedCargoes = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginUser = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainHistorical = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PerformedCargoes = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PerformedCargoesFooter = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PerformedCargoesHeader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PerformedCargoesMain = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PreSelectionRegister = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SearchCargoes = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int UserRegister = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Exit = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Login = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int country_prompt = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
