#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppCargoExpressFinal.Resource", IsApplication=true)]

namespace AppCargoExpressFinal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::AppCargoExpressFinal.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::AppCargoExpressFinal.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camionero = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cargoExpress = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int userIcon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int btnCfReturn = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int btnLUAHistorical = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int btnLUAModifyRegister = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btnLUAPublishCargo = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btnLUAPublishTravel = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int btnLUAReturn = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int btnLUASearchCargo = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int btnLUASearchTravel = 2131034120;
			
			// aapt resource value: 0x7f050017
			public const int btnMLogin = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int btnMLogout = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int btnMhAwardedCargoes = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int btnMhPerformedCargoes = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int btnMhReturn = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int btnMhSeeRank = 2131034140;
			
			// aapt resource value: 0x7f05002b
			public const int btnPSRCarrier = 2131034155;
			
			// aapt resource value: 0x7f05002d
			public const int btnPSRIngresar = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int btnPSRReturn = 2131034158;
			
			// aapt resource value: 0x7f05002a
			public const int btnPSRUser = 2131034154;
			
			// aapt resource value: 0x7f050039
			public const int btnScClean = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int btnScReturn = 2131034170;
			
			// aapt resource value: 0x7f050038
			public const int btnScSearch = 2131034168;
			
			// aapt resource value: 0x7f050050
			public const int btnUrRegister = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int btnUrReturn = 2131034193;
			
			// aapt resource value: 0x7f050012
			public const int chkMRecord = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int imgMView1 = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int lblChTitleList = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int lblMPass = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int lblMRegister = 2131034133;
			
			// aapt resource value: 0x7f05000e
			public const int lblMUser = 2131034126;
			
			// aapt resource value: 0x7f050019
			public const int lblMhMainTitle = 2131034137;
			
			// aapt resource value: 0x7f050025
			public const int lblPSRRegister = 2131034149;
			
			// aapt resource value: 0x7f05002c
			public const int lblPSRSelectUserMsg = 2131034156;
			
			// aapt resource value: 0x7f050027
			public const int lblPSRtypeOfUser = 2131034151;
			
			// aapt resource value: 0x7f050034
			public const int lblScCargoType = 2131034164;
			
			// aapt resource value: 0x7f050032
			public const int lblScDestiny = 2131034162;
			
			// aapt resource value: 0x7f050030
			public const int lblScOrigin = 2131034160;
			
			// aapt resource value: 0x7f050036
			public const int lblScPriceRange = 2131034166;
			
			// aapt resource value: 0x7f05002f
			public const int lblScTitle = 2131034159;
			
			// aapt resource value: 0x7f05004c
			public const int lblUrAddress = 2131034188;
			
			// aapt resource value: 0x7f050040
			public const int lblUrAlias = 2131034176;
			
			// aapt resource value: 0x7f050046
			public const int lblUrCodArea = 2131034182;
			
			// aapt resource value: 0x7f05004e
			public const int lblUrComuna = 2131034190;
			
			// aapt resource value: 0x7f05004a
			public const int lblUrMail = 2131034186;
			
			// aapt resource value: 0x7f050042
			public const int lblUrPass = 2131034178;
			
			// aapt resource value: 0x7f050044
			public const int lblUrPhone = 2131034180;
			
			// aapt resource value: 0x7f050048
			public const int lblUrPhone2 = 2131034184;
			
			// aapt resource value: 0x7f05003e
			public const int lblUrUserLastName = 2131034174;
			
			// aapt resource value: 0x7f05003c
			public const int lblUrUserName = 2131034172;
			
			// aapt resource value: 0x7f050029
			public const int linearLayout1 = 2131034153;
			
			// aapt resource value: 0x7f050000
			public const int lstAc = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int lstAcAwarded = 2131034113;
			
			// aapt resource value: 0x7f050023
			public const int lstPcPerformed = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int psrSpc2 = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int spcPSR3 = 2131034152;
			
			// aapt resource value: 0x7f050035
			public const int sprScCargoType = 2131034165;
			
			// aapt resource value: 0x7f050033
			public const int sprScDestiny = 2131034163;
			
			// aapt resource value: 0x7f050031
			public const int sprScOrigin = 2131034161;
			
			// aapt resource value: 0x7f050037
			public const int sprScPriceRange = 2131034167;
			
			// aapt resource value: 0x7f05004f
			public const int sprUrCity = 2131034191;
			
			// aapt resource value: 0x7f050013
			public const int tblMLayout1 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int tblMRow1 = 2131034132;
			
			// aapt resource value: 0x7f05003b
			public const int textView1 = 2131034171;
			
			// aapt resource value: 0x7f050004
			public const int txtLUAWelcomeUser = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int txtMPassword = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int txtMReset = 2131034134;
			
			// aapt resource value: 0x7f05000f
			public const int txtMUserName = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int txtMWelcomeUser = 2131034124;
			
			// aapt resource value: 0x7f050024
			public const int txtPSRWelcomeUser = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int txtPcCargoType = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int txtPcDate = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int txtPcOriginDestiny = 2131034144;
			
			// aapt resource value: 0x7f05001e
			public const int txtPcUser = 2131034142;
			
			// aapt resource value: 0x7f050022
			public const int txtPcValue = 2131034146;
			
			// aapt resource value: 0x7f05004d
			public const int txtUrAddress = 2131034189;
			
			// aapt resource value: 0x7f050041
			public const int txtUrAlias = 2131034177;
			
			// aapt resource value: 0x7f050047
			public const int txtUrCodArea = 2131034183;
			
			// aapt resource value: 0x7f05004b
			public const int txtUrMail = 2131034187;
			
			// aapt resource value: 0x7f050043
			public const int txtUrPassword = 2131034179;
			
			// aapt resource value: 0x7f050045
			public const int txtUrPhone = 2131034181;
			
			// aapt resource value: 0x7f050049
			public const int txtUrPhone2 = 2131034185;
			
			// aapt resource value: 0x7f05003f
			public const int txtUrUserLastName = 2131034175;
			
			// aapt resource value: 0x7f05003d
			public const int txtUrUserName = 2131034173;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AwardedCargoes = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AwardedCargoesMain = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CargoesFooter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CargoesHeader = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoginUser = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainHistorical = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PerformedCargoes = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PerformedCargoesMain = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PreSelectionRegister = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SearchCargoes = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int UserRegister = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int AwardedCargoesTitle = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Exit = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Login = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int PerformedCargoesTitle = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int PublishedTripTitle = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int country_prompt = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
